### PR TITLE
Update proxmox.md

### PR DESCRIPTION
**Pull request by EWANZO101**

### CODE REVIEW

**Review by PadowYT2 — CHANGES_REQUESTED** [review]
Thank you, but you shouldn't be using Discord CDN. Please upload the images into the assets folder (and proxmox in there). Also please crop browser tabs (such as the URL bar)

**Review by EWANZO101 — COMMENTED** [review]
hope this fixed

**Review by PadowYT2 — CHANGES_REQUESTED** [review]
You didn't change the actual links in the proxmox page, also you must embed the images:
```
![1](image url)
```

The images must be in the `assets/proxmox` folder

The files should be properly named

**Review by EWANZO101 — COMMENTED** [review]
Hello this should be it as it did it turns out it did not save correctly

**Comment by PadowYT2** [comment]
https://canary.discord.com/channels/760945720470667294/1129104624033468466/1187859389353312296

**Comment by EWANZO101** [comment]
> https://canary.discord.com/channels/760945720470667294/1129104624033468466/1187859389353312296

i updated the discord thing all images and text should be correct 
Screenshot 2023-12-22 205615

**Pull request closed without merging**
